# python中神奇的切片

In [2]:
import os
import numpy as np

## 1. 什么是切片？

切片就是从一个元素序列中获取子集。

如果一种编程语言没有提供特殊的切片操作，
这需要自己编写程序完成这种操作。

下面先来见识一下python中的切片操作。

In [8]:
a_list = list(range(10))
print('a_list =', a_list)

# 获取a_list中第5到第8个元素
b_list = [x for idx, x in enumerate(a_list) if idx >= 4 and idx <= 7]
print('b_list =', b_list)

# 获取a_list中索引为偶数的元素
c_list = [x for idx, x in enumerate(a_list) if idx % 2 == 0]
print('c_list = ', c_list)

# 使用python中的切片操作
da_list = a_list[4:8]
db_list = a_list[::2]
print('da_list = ', da_list)
print('db_list = ', db_list)

a_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b_list = [4, 5, 6, 7]
c_list =  [0, 2, 4, 6, 8]
da_list =  [4, 5, 6, 7]
db_list =  [0, 2, 4, 6, 8]


## 2. 怎样设置切片的参数？

切片确实比自己手动用循环和分支结构编写程序要方便很多，而且代码简洁。

接下来就需要了解切片的参数以便灵活运用切片了。

In [26]:
# 切片参数  start_index : end_index : step，
# 前闭后开，包含start_index, 不包含end_index
a_list = list(range(10))
print('a_list =', a_list)
# 获取索引3到索引7之间(前闭后开)索引为奇数的元素
b_list = a_list[3:7:2]
print('b_list = ', b_list)

# 省略start_index，则该参数默认为0
c_list = a_list[:7:2]
print('c_list = ', c_list)

# 省略end_index，则该参数默认包含序列最后一个元素
d_list = a_list[3::2]
print('d_list = ', d_list)

# 省略step，则该参数默认为 1
e_list = a_list[3:7]
print('e_list = ', e_list)

# 全都省略，则表示取所有元素
f_list = a_list[:]
print('f_list = ', f_list)

a_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b_list =  [3, 5]
c_list =  [0, 2, 4, 6]
d_list =  [3, 5, 7, 9]
e_list =  [3, 4, 5, 6]
f_list =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## 3. 神奇的效果

In [20]:
a_list = list(range(10))
print('a_list =', a_list)

# 取倒数第4个到倒数第1个元素
b_list = a_list[-4:-1]
print('b_list = ', b_list)

# 取序列元素的倒序
c_list = a_list[::-1]
print('c_list = ', c_list)

# 取索引为7到索引为2的元素
d_list = a_list[7:2:-1]
print('d_list = ', d_list)

# 取倒数第1个到倒数第4个元素
e_list = a_list[-1:-4:-1]
print('e_list = ', e_list)

a_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b_list =  [6, 7, 8]
c_list =  [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
d_list =  [7, 6, 5, 4, 3]
e_list =  [9, 8, 7]


## 4. numpy中的切片

In [3]:
arr = np.array(range(25))
arr = np.reshape(arr, (5,5))
print('arr =', arr)

# 取第2到第4行
b_arr = arr[2:5, :]
print('b_arr = ', b_arr)

# 取第2到第4列
c_arr = arr[:, 2:5]
print('c_arr = ', c_arr)

# 二维切片, 第一个是行切片，第二个是列切片
d_arr = arr[0:4:2, -1:-3:-1]
print('d_arr = ', d_arr)

# 省略号
e_arr = arr[0:2, ...]
print('e_arr = ', e_arr)

arr = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
b_arr =  [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
c_arr =  [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]
d_arr =  [[ 4  3]
 [14 13]]
e_arr =  [[0 1 2 3 4]
 [5 6 7 8 9]]
