# <center>numpy的12个基本操作</center>

By [青衣极客 Blue Geek](https://mp.weixin.qq.com/s/JgSmnhg9MqVrcdJurkk-wg)

In 2019-09-17

1. 创建数组
2. 数组索引
3. 扩展矩阵
4. 改变形状
5. 转置类操作
6. 改变维度
7. 拼接数组
8. 切分数组
9. 增加和移除元素
10. 广播
11. 基本运算
12. save和load

In [77]:
import os
import sys
import numpy as np

## 1. 创建数组

In [78]:
# 从list创建数组
print(np.array([1,2,3,4,5]))             # 一维数组
print(np.array([[1,2,3], [4,5,6]]))      # 二维数组
print(np.array([1,2,3], dtype=np.float)) # 指定元素数据类型
print(np.zeros((1,3), dtype=np.int64))   # 创建全0的数组
print(np.ones((1,3), dtype=np.float))    # 创建全1的数组
print(np.eye(2, dtype=np.float))         # 创建单位矩阵
print(np.arange(1, 10, 2))               # 创建均匀的整数数组
print(np.linspace(1, 3, 4))              # 创建线性数组
print(np.random.random((1,3)))           # 创建随机数组

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[1. 2. 3.]
[[0 0 0]]
[[1. 1. 1.]]
[[1. 0.]
 [0. 1.]]
[1 3 5 7 9]
[1.         1.66666667 2.33333333 3.        ]
[[0.5003854  0.59875968 0.79207667]]


## 2. 数组索引

In [79]:
a = np.random.random((3,3))
print(a[0][0])      # 直接索引
print(a>0.5)        # 条件蒙版
print(a[a>0.5])     # 蒙版索引
print(a[1, 2])      # 切片索引

0.4059516560746701
[[False False False]
 [ True False  True]
 [ True False  True]]
[0.95266423 0.88453931 0.72445232 0.90560359]
0.8845393115697767


## 3. 扩展矩阵

In [80]:
a = np.array([[1,2,3]])
print(np.tile(a, [3,1]))
print(a.repeat(3, axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


## 4. 改变形状

In [81]:
a = np.array([1,2,3,4])
b = a.reshape((2,2))       # 指定目标形状
print(b)
print(b.flatten())         # 压平成一维数组
a.resize(2,2)              # 直接修改
print(a)

[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]


## 5. 转置类的操作

In [90]:
a = np.array([[1,2], [3,4]], dtype=np.float)
print('a.transpose() = ', a.transpose())    # 计算数组转置
print('a.T = ', a.T)                        # 同样是转置

b = np.array(list(range(16)))
b = b.reshape([2,2,4])
print('b = ', b)
c = np.rollaxis(b, 2)          # 将坐标轴axis=2转到axis=0
print('c = ', c)
print('np.mean(b, axis=2) = ', np.mean(b, axis=2))
# 对axis=2的坐标轴上所有元素减去该轴上的均值
print('c - np.mean(b, axis=2) = ', c - np.mean(b, axis=2))

d = np.swapaxes(b, 2, 1)
print('d = ', d)

a.transpose() =  [[1. 3.]
 [2. 4.]]
a.T =  [[1. 3.]
 [2. 4.]]
b =  [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
c =  [[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]]
np.mean(b, axis=2) =  [[ 1.5  5.5]
 [ 9.5 13.5]]
c - np.mean(b, axis=2) =  [[[-1.5 -1.5]
  [-1.5 -1.5]]

 [[-0.5 -0.5]
  [-0.5 -0.5]]

 [[ 0.5  0.5]
  [ 0.5  0.5]]

 [[ 1.5  1.5]
  [ 1.5  1.5]]]
d =  [[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


## 6. 改变维度

In [83]:
a = np.array([[1,2], [3,4]])
b = a.reshape((1, -1))
print('b.shape = ', b.shape)
c = b.squeeze()                # 去掉维度为1的坐标轴
print('c.shape = ', c.shape)
d = np.expand_dims(c, axis=1)  # 在扩展指定坐标轴的维度为1
print('d.shape = ', d.shape)

b.shape =  (1, 4)
c.shape =  (4,)
d.shape =  (4, 1)


## 7. 拼接数组

In [84]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6], [7,8]])
c = np.concatenate((a, b), axis=1)  # 在指定坐标轴上拼接数组
print('c = ', c)
d = np.stack([a,b])                 # 拼接数组到一个新的坐标轴
print(d)


c =  [[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 8. 切分数组

In [85]:
a = np.arange(9)
print(np.split(a, [3,5,6,8]))  # 按照指定切分点对原数组进行切分

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7]), array([8])]


## 9. 增加和移除元素

In [86]:
a = np.arange(8)
a = a.reshape((2,4))

c = np.delete(a, [0,2], axis=1)  # 在指定坐标轴上删除指定切片
print('c = ', c)

d = np.insert(a, 1, 5, axis=1)   # 在指定坐标轴的指定切片处插入指定数值  
print('d = ', d)

c =  [[1 3]
 [5 7]]
d =  [[0 5 1 2 3]
 [4 5 5 6 7]]


## 10. 广播
1. 坐标轴不足的向最标轴最多的看齐
2. 结果数组的形状由参与计算的各数组各坐标轴维度最大的确定
3. 在对应坐标轴上，只有输入数组的维度为1，或者与输出数组相同才可计算
4. 对坐标轴维度为1的数组进行扩展时，就是不断复制该维度

In [87]:
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a+b)    # 相当于先调用repeat函数把两个输入数组变成同样形状，然后计算

[[5 6 7]
 [6 7 8]
 [7 8 9]]


## 11. 基本运算

In [91]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# 加法
print('a+b = ', a+b)

# 乘法
print(a.dot(b))            # 矩阵乘法
print('a*b = ', a*b)       # 元素乘法

# 矩阵求逆
print(np.linalg.inv(a))  # 矩阵求逆
print(a.dot(np.linalg.inv(a)))

a+b =  [[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
a*b =  [[ 5 12]
 [21 32]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## 12. save和load

In [89]:
a = np.arange(16)
print('a = ', a)
save_path = '../output/np_save.npy'
np.save(save_path, a)    # 将数组写入到文件

b = np.load(save_path)   # 从文件中载入
print('b = ', b)

a =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
b =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
